name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  semver:
    uses: lsc-sde/lsc-sde/.github/workflows/semver.yaml@main
    with:
      useConfigFile: true

  build:
    uses: lsc-sde/lsc-sde/.github/workflows/acr-build.yaml@main
    needs: semver
    with:
      repository: datascience
      imageName: datascience-notebook
      azureSubscriptionId: ${{ vars.SANDBOX_AZURE_SUBSCRIPTION_ID }}
      azureClientId: ${{ vars.SANDBOX_AZURE_CLIENT_ID }}
      azureTenantId: ${{ vars.SANDBOX_AZURE_TENANT_ID }}
      azureContainerRegistry: ${{ vars.SANDBOX_AZURE_CONTAINER_REGISTRY }}
      azureKeyVault: ${{ vars.SANDBOX_AZURE_KEY_VAULT }}
      version: ${{ needs.semver.outputs.GitVersion_SemVer }}