name: Sandbox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    uses: lsc-sde/lsc-sde/.github/workflows/acr-build.yaml@main
    with:
      repository: datascience
      imageName: datascience-notebook
      azureSubscriptionId: ${{ vars.SANDBOX_AZURE_SUBSCRIPTION_ID }}
      azureClientId: ${{ vars.SANDBOX_AZURE_CLIENT_ID }}
      azureTenantId: ${{ vars.SANDBOX_AZURE_TENANT_ID }}
      azureContainerRegistry: ${{ vars.SANDBOX_AZURE_CONTAINER_REGISTRY }} #.azurecr.io
      azureKeyVault: ${{ vars.SANDBOX_AZURE_KEY_VAULT }} #